# #######################################################################################
# HYPRLAND MAIN CONFIG
# #######################################################################################

# Sourcing external config files
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/programs.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/windowrules.conf
source = ~/.config/hypr/config/autostart.conf