# Autostart necessary processes (like notifications daemons, status bars, etc.)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = waybar &
exec-once = mako &
exec-once = awww-daemon &
exec-once = waypaper --restore
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle &
exec-once = /usr/bin/lxqt-policykit-agent &
