windowrule {
    name = pavucontrol-float
    match:class = ^(org.pulseaudio.pavucontrol)$
    float = on
    size = 820 600
    center = on
}

windowrule {
    name = nm-connection-float
    match:class = ^(nm-connection-editor)$
    float = on
}

windowrule {
    name = blueman-float
    match:class = ^(blueman-manager)$
    float = on
}

windowrule {
    name = global-suppress-maximize
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = prism-launcher-float
    match:class = ^(org.prismlauncher.PrismLauncher)$
    float = on
    size = 820 600
    center = on
}

windowrule {
    name = steam-float
    match:class = ^(steam)$
    float = on
}

windowrule {
    name = mpv-float
    match:class = ^(mpv)$
    float = on
}

windowrule {
    name = waypaper-float
    match:class = ^(waypaper)$
    float = on
}
# wlogout blur
layerrule = blur on, match:namespace logout_dialog
layerrule = ignore_alpha 0.1, match:namespace logout_dialog
